# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='password',
        ),
    ]
