# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasesapp', '0002_remove_database_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
